name: continuation_token
description: Encode and decode continuation token values for stateless pagination APIs.
version: 1.0.0
homepage: https://github.com/isoos/continuation-token
author: Istvan Soos <istvan.soos@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
