name: continuation_token
description: Encode and decode continuation token values for stateless pagination APIs.
version: 2.1.0
homepage: https://github.com/isoos/continuation-token

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
